name: Docker Image CI

on:
  push:
    branches: [ Dev ]
  pull_request:
    branches: [ Dev ]

  workflow_dispatch:

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      -
        name: Extract metadata for Docker (tags, labels)
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USER_TEST }}/ai_ml_4dstem_test
          tags: |
            type=raw,value=latest,enable=${{ endsWith(Github.ref, steps.extract_branch.outputs.branch) }}
            type=ref,event=tag
      - 
        name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_TEST }}
          password: ${{ secrets.DOCKERHUB_TOKEN_TEST }}
      - 
        name: Build and push to DockerHub
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: DockerFiles/prismatic-pymatgen-dask-Dockerfile-alpha-7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
